name: usersecure_flutter
description: A free AI Username & Password Generator app.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # AdMob
  google_mobile_ads: ^4.0.0

  # Material Icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
